stages:
  # - unit-test
  - rebuild-container

getVersion:
  stage: .pre
  script:
    - echo "TAG=$CI_COMMIT_TAG" > tag.env
    - echo "COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" > short_sha.env
  artifacts:
    expire_in: never
    paths:
      - ./
    reports:
      dotenv:
        - tag.env
        - short_sha.env

# unitTestJob:
#   stage: unit-test
#   only:
#     - tags
#   except:
#     - branches
#   variables:
#     GIT_SUBMODULE_STRATEGY: recursive
#     GIT_SUBMODULE_UPDATE_FLAGS: --remote --merge
#   script:
#     - echo "Start unit-test..."
#     # -v - развернутая информация / x - вывод информации до первой ошибки
#     - /home/gitlab-runner/venv3.12/bin/pytest -v -x

rebuildContainerJob:
  stage: rebuild-container
  only:
    - tags
  except:
    - branches
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_UPDATE_FLAGS: --remote --merge
  script:
    - echo "Rebuild container..."
    - docker compose down --rmi all && docker compose up -d
