scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.0.110:9100']
  - job_name: rabbitMQ
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.110:15692']
  - job_name: postgresql
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.110:9187']